$(document).ready(function(){

	
	$(".black").hide();         //hides other buttons until user clicks
	$(".clear").hide();			//'new grid size'
	$(".random").hide();
	$(".gradient").hide();
	$(".trail").hide();

	
	$(".new").click(function(){     
		
		$("#welcome").hide();		//hides welcome message
		
		var ask = prompt("Choose a number between 24 and 128.");
		
		if (ask >= 24 && ask <= 128) {     //change the number of divs
										   //to user's selection
			var size = 960;
			var boxSize = (960 - 2*ask)/ask;
			
			var container = $(".squares").html("");
			for(var i = 0; i <= ask; i++) {
				for(var j = 0; j <= ask; j++) {
					container.append($("<div></div>").addClass("grid").height(boxSize).width(boxSize));
				};
				container.append($("<div></div>").css("clear", "both"));
			};

			/* note: because some of the buttons apply css other than color, such as gradient or trail, those buttons must be turned off once another is selected, hence '$(this).off('mouseenter.class') */

			$('.grid').mouseenter(function(){
				$(this).css("background-color", "black");
			});
			
			$(".clear").click(function(){
				$('.grid').css("background-color", "white");
				$('.grid').css("opacity", 1);
				$(".grid").off('mouseenter.trail');
				$(".grid").off('mouseenter.gradient');
			});
			
			/* random colors generated by returning a random rgb value each time the mouse enters a div */

			var get_random_color = function() {
  				var r = function() { return Math.floor(Math.random()*256) };
  				return "rgb(" + r() + "," + r() + "," + r() + ")";
			};
			
			$(".random").click(function(){
				$(".grid").mouseenter(function(){
					$(this).css("background-color", get_random_color);

				});
				$(this).css("opacity", 1);
				$(".grid").off('mouseenter.trail');
				$(".grid").off('mouseenter.gradient');
			});

			$(".gradient").click(function(){
				$(".grid").on('mouseenter.gradient', function(){
					$(this).css("background-color", "black");
					$(this).css("opacity", $(this).css("opacity") * 0.7);
				});
				$(".grid").off('mouseenter.trail');
			});

			$(".black").click(function(){
				$(".grid").mouseenter(function(){
					$(this).css("background-color", "black");
				});
				$(this).css("opacity", 1);
				$(".grid").off('mouseenter.trail');
				$(".grid").off('mouseenter.gradient');
			});

			
			$(".trail").click(function(){
				$(".grid").on('mouseenter.trail', function(){
					$(this).css("background-color", "black");				
					$(this).fadeTo(0,0);
					$(this).mouseleave(function(){
						$(this).fadeTo(600,1);
					});
				});
				$(".grid").off('mouseenter.gradient');
			});

		}

		else {
			alert("I'm sorry, but that number won't work. Choose a number between 24 and 128.");
			/* alert instead of prompt so user doesn't have to refresh the page, but can just reclick 'new grid size' */
		};

		//show other buttons once 'new grid size' is initially clicked
		
		$(".black").show();
		$(".clear").show();
		$(".random").show();
		$(".gradient").show();
		$(".trail").show();

	});


});